//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sVien
    {
        public int maSV { get; set; }
        public string hoten { get; set; }
        public System.DateTime ngsinh { get; set; }
        public string khoa { get; set; }
        public string lop { get; set; }
        public string hedaotao { get; set; }
    }
}
